name: Deploy Laravel API to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H 3.12.148.12 >> ~/.ssh/known_hosts

      - name: Create PEM file
        run: echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/your-key.pem

      - name: Set PEM file permissions
        run: chmod 400 /tmp/your-key.pem

      - name: Deploy to EC2 via SSH
        run: ssh -i /tmp/your-key.pem ubuntu@3.12.148.12 'cd /var/www/minha-api-ec2 && git pull && composer install'
